package ch.klara.luz.store;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CSerializer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CSerializer() {
    }




}