package ch.klara.luz.store;

import java.io.IOException;
import java.time.LocalDate;
import java.time.ZoneOffset;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class CSerializer extends JsonSerializer<LocalDate> {

    public void serialize(LocalDate date, JsonGenerator generator, SerializerProvider provider) throws IOException {
		generator.writeNumber(date.atStartOfDay().atZone(ZoneOffset.UTC).toEpochSecond());
	}
}