package ch.klara.luz.store.rules;


import ch.klara.luz.store.model.ProductPricing;
import ch.klara.luz.store.model.CustomerPricingModel;
import java.time.LocalDate;
import java.lang.Number;

dialect "mvel"

rule "Price plan is SINGLE"
	when
		$productPricing : ProductPricing( pricePlan == "SINGLE" )
	then
		$productPricing.setPrice(3.0B);
end

rule "Price plan is VOLUME"
    when
        $productPricing: ProductPricing(pricePlan == "VOLUME", $volume : volume )
    then
        $productPricing.setPrice(2.0B * $volume);
end

rule "Product code is POS"
    when
        $productPricing: ProductPricing(productCode contains "POS" && pricePlan == "MONTHLY")
    then
        $productPricing.setPrice(49.0B);
end

rule "Product code is BOOKING"
    when
        $productPricing: ProductPricing(productCode contains "BOOKING" && pricePlan == "MONTHLY")
    then
        $productPricing.setPrice(79.0B);
end

rule "Price plan is MONTHLY"
    when
        $productPricing: ProductPricing(productCode not contains "POS" && productCode not contains "BOOKING" && pricePlan == "MONTHLY")
    then
        $productPricing.setPrice(39.0B);
end

rule "Price plan is QUARTERLY"
    when
        $productPricing: ProductPricing(pricePlan == "QUARTERLY")
    then
        $productPricing.setPrice(100.0B);
end

rule "Price plan is YEARLY"
    when
        $productPricing: ProductPricing(pricePlan == "YEARLY")
    then
        $productPricing.setPrice(400.0B);
end

rule "Customer legal form is EU and price plan is yearly"
    when
        $productPricing: ProductPricing(pricePlan == "YEARLY");
        $customer: CustomerPricingModel(legalForm == "EU");
    then
        $productPricing.setPrice(399.15B);
        $productPricing.setTestingDuration("30D");
end

rule "Customer loyalty since first day of year 2018 and price plan is QUARTERLY"
    when
        $productPricing: ProductPricing(pricePlan == "QUARTERLY");
        $date: LocalDate() from LocalDate.of(2018, 1, 1);
        $customer: CustomerPricingModel(customerSinceDate.isEqual($date));
    then
        $productPricing.setPrice(211.0B);
        $productPricing.setTestingDuration("10D");
        $productPricing.setKlaraPoints(10);
end
