package ch.klara.luz.store.model;

import java.util.Date;
import java.time.LocalDate;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import ch.klara.luz.store.CSerializer;
import ch.klara.luz.store.CDeserializer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerPricingModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String legalForm;
	private java.lang.String nogaCode;
	private java.lang.String region;

	@com.fasterxml.jackson.databind.annotation.JsonSerialize(using = CSerializer.class)
	@com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = CDeserializer.class)
	private LocalDate customerSinceDate;

	private java.util.Date birthdate;

	public CustomerPricingModel() {
	}

	public java.lang.String getLegalForm() {
		return this.legalForm;
	}

	public void setLegalForm(java.lang.String legalForm) {
		this.legalForm = legalForm;
	}

	public java.lang.String getNogaCode() {
		return this.nogaCode;
	}

	public void setNogaCode(java.lang.String nogaCode) {
		this.nogaCode = nogaCode;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.time.LocalDate getCustomerSinceDate() {
		return this.customerSinceDate;
	}

	public void setCustomerSinceDate(java.time.LocalDate customerSinceDate) {
		this.customerSinceDate = customerSinceDate;
	}

	public java.util.Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(java.util.Date birthdate) {
		this.birthdate = birthdate;
	}

	public CustomerPricingModel(java.lang.String legalForm,
			java.lang.String nogaCode, java.lang.String region,
			java.time.LocalDate customerSinceDate, java.util.Date birthdate) {
		this.legalForm = legalForm;
		this.nogaCode = nogaCode;
		this.region = region;
		this.customerSinceDate = customerSinceDate;
		this.birthdate = birthdate;
	}

}