package ch.klara.luz.store.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerPricingModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String legalForm;
	private java.math.BigDecimal turnover;
	private java.lang.String nogaCode;
	private java.lang.String region;
	private java.time.LocalDate customerSinceDate;

	private int numberOfEmployees;

	public CustomerPricingModel() {
	}

	public java.lang.String getLegalForm() {
		return this.legalForm;
	}

	public void setLegalForm(java.lang.String legalForm) {
		this.legalForm = legalForm;
	}

	public java.math.BigDecimal getTurnover() {
		return this.turnover;
	}

	public void setTurnover(java.math.BigDecimal turnover) {
		this.turnover = turnover;
	}

	public java.lang.String getNogaCode() {
		return this.nogaCode;
	}

	public void setNogaCode(java.lang.String nogaCode) {
		this.nogaCode = nogaCode;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.time.LocalDate getCustomerSinceDate() {
		return this.customerSinceDate;
	}

	public void setCustomerSinceDate(java.time.LocalDate customerSinceDate) {
		this.customerSinceDate = customerSinceDate;
	}

	public int getNumberOfEmployees() {
		return this.numberOfEmployees;
	}

	public void setNumberOfEmployees(int numberOfEmployees) {
		this.numberOfEmployees = numberOfEmployees;
	}

	public CustomerPricingModel(java.lang.String legalForm,
			java.math.BigDecimal turnover, java.lang.String nogaCode,
			java.lang.String region, java.time.LocalDate customerSinceDate,
			int numberOfEmployees) {
		this.legalForm = legalForm;
		this.turnover = turnover;
		this.nogaCode = nogaCode;
		this.region = region;
		this.customerSinceDate = customerSinceDate;
		this.numberOfEmployees = numberOfEmployees;
	}

}