package ch.klara.luz.store.model;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerPricingModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String legalForm;
	private java.lang.String nogaCode;
	private java.lang.String region;
	private Date customerSinceDate;

	public CustomerPricingModel() {
	}

	public java.lang.String getLegalForm() {
		return this.legalForm;
	}

	public void setLegalForm(java.lang.String legalForm) {
		this.legalForm = legalForm;
	}

	public java.lang.String getNogaCode() {
		return this.nogaCode;
	}

	public void setNogaCode(java.lang.String nogaCode) {
		this.nogaCode = nogaCode;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.util.Date getCustomerSinceDate() {
		return this.customerSinceDate;
	}

	public void setCustomerSinceDate(java.util.Date customerSinceDate) {
		this.customerSinceDate = customerSinceDate;
	}

	public CustomerPricingModel(java.lang.String legalForm,
			java.lang.String nogaCode, java.lang.String region,
			java.util.Date customerSinceDate) {
		this.legalForm = legalForm;
		this.nogaCode = nogaCode;
		this.region = region;
		this.customerSinceDate = customerSinceDate;
	}

}