package ch.klara.luz.store.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductPricing implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String productCode;
	private int volume;
	private java.lang.String pricePlan;
	private java.math.BigDecimal price;

	private int klaraPoints;

	private java.lang.String testingDuration;

	private java.util.Date requestDate;

	private java.math.BigDecimal vatRate;

	private boolean vatIncluded;

	@org.kie.api.definition.type.Description(value = "Indicate the promotion code (special discount of product price)")
	private java.lang.String promotionCode;

	@org.kie.api.definition.type.Description(value = "Represent the discount amount, can be a percentage or fixed amount\nE.g. 30%, 250 CHF")
	private java.lang.String discount;

	public ProductPricing() {
	}

	public java.lang.String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(java.lang.String productCode) {
		this.productCode = productCode;
	}

	public int getVolume() {
		return this.volume;
	}

	public void setVolume(int volume) {
		this.volume = volume;
	}

	public java.lang.String getPricePlan() {
		return this.pricePlan;
	}

	public void setPricePlan(java.lang.String pricePlan) {
		this.pricePlan = pricePlan;
	}

	public java.math.BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(java.math.BigDecimal price) {
		this.price = price;
	}

	public int getKlaraPoints() {
		return this.klaraPoints;
	}

	public void setKlaraPoints(int klaraPoints) {
		this.klaraPoints = klaraPoints;
	}

	public java.lang.String getTestingDuration() {
		return this.testingDuration;
	}

	public void setTestingDuration(java.lang.String testingDuration) {
		this.testingDuration = testingDuration;
	}

	public java.util.Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(java.util.Date requestDate) {
		this.requestDate = requestDate;
	}

	public java.math.BigDecimal getVatRate() {
		return this.vatRate;
	}

	public void setVatRate(java.math.BigDecimal vatRate) {
		this.vatRate = vatRate;
	}

	public boolean isVatIncluded() {
		return this.vatIncluded;
	}

	public void setVatIncluded(boolean vatIncluded) {
		this.vatIncluded = vatIncluded;
	}

	public java.lang.String getPromotionCode() {
		return this.promotionCode;
	}

	public void setPromotionCode(java.lang.String promotionCode) {
		this.promotionCode = promotionCode;
	}

	public java.lang.String getDiscount() {
		return this.discount;
	}

	public void setDiscount(java.lang.String discount) {
		this.discount = discount;
	}

	public ProductPricing(java.lang.String productCode, int volume,
			java.lang.String pricePlan, java.math.BigDecimal price,
			int klaraPoints, java.lang.String testingDuration,
			java.util.Date requestDate, java.math.BigDecimal vatRate,
			boolean vatIncluded, java.lang.String promotionCode,
			java.lang.String discount) {
		this.productCode = productCode;
		this.volume = volume;
		this.pricePlan = pricePlan;
		this.price = price;
		this.klaraPoints = klaraPoints;
		this.testingDuration = testingDuration;
		this.requestDate = requestDate;
		this.vatRate = vatRate;
		this.vatIncluded = vatIncluded;
		this.promotionCode = promotionCode;
		this.discount = discount;
	}

}